# pylint: reportAttributeAccessIssue=false

"""initial_schema_clean

Revision ID: 1438202fec93
Revises:
Create Date: 2025-12-23 13:47:47.794988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from cognee.modules.notebooks.models.Notebook import NotebookCellList


# revision identifiers, used by Alembic.
revision: str = '1438202fec93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('extension', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('original_extension', sa.String(), nullable=True),
    sa.Column('original_mime_type', sa.String(), nullable=True),
    sa.Column('loader_engine', sa.String(), nullable=True),
    sa.Column('raw_data_location', sa.String(), nullable=True),
    sa.Column('original_data_location', sa.String(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('raw_content_hash', sa.String(), nullable=True),
    sa.Column('external_metadata', sa.JSON(), nullable=True),
    sa.Column('node_set', sa.JSON(), nullable=True),
    sa.Column('pipeline_status', sa.JSON(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('data_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_owner_id'), 'data', ['owner_id'], unique=False)
    op.create_index(op.f('ix_data_tenant_id'), 'data', ['tenant_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_owner_id'), 'datasets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_datasets_tenant_id'), 'datasets', ['tenant_id'], unique=False)
    op.create_table('graph_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('num_tokens', sa.Integer(), nullable=True),
    sa.Column('num_nodes', sa.Integer(), nullable=True),
    sa.Column('num_edges', sa.Integer(), nullable=True),
    sa.Column('mean_degree', sa.Float(), nullable=True),
    sa.Column('edge_density', sa.Float(), nullable=True),
    sa.Column('num_connected_components', sa.Integer(), nullable=True),
    sa.Column('sizes_of_connected_components', sa.JSON(), nullable=True),
    sa.Column('num_selfloops', sa.Integer(), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('avg_shortest_path_length', sa.Float(), nullable=True),
    sa.Column('avg_clustering', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_relationship_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('destination_node_id', sa.UUID(), nullable=False),
    sa.Column('creator_function', sa.String(), nullable=False),
    sa.Column('node_label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_graph_relationship_id', 'graph_relationship_ledger', ['id'], unique=False)
    op.create_index('idx_graph_relationship_ledger_destination_node_id', 'graph_relationship_ledger', ['destination_node_id'], unique=False)
    op.create_index('idx_graph_relationship_ledger_source_node_id', 'graph_relationship_ledger', ['source_node_id'], unique=False)
    op.create_table('notebooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cells', NotebookCellList(), nullable=False),
    sa.Column('deletable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebooks_owner_id'), 'notebooks', ['owner_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DATASET_PROCESSING_INITIATED', 'DATASET_PROCESSING_STARTED', 'DATASET_PROCESSING_COMPLETED', 'DATASET_PROCESSING_ERRORED', name='pipelinerunstatus'), nullable=True),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_name', sa.String(), nullable=True),
    sa.Column('pipeline_id', sa.UUID(), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('run_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_dataset_id'), 'pipeline_runs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_pipeline_id'), 'pipeline_runs', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_pipeline_run_id'), 'pipeline_runs', ['pipeline_run_id'], unique=False)
    op.create_table('principals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_principals_id'), 'principals', ['id'], unique=False)
    op.create_table('pipelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('executable', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_task',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pipeline', sa.UUID(), nullable=False),
    sa.Column('task', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline'], ['pipelines.id'], ),
    sa.ForeignKeyConstraint(['task'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('pipeline', 'task')
    )
    op.create_table('task_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('run_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('query_type', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('query_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_user_id'), 'results', ['user_id'], unique=False)
    op.create_table('sync_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='syncstatus'), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('dataset_ids', sa.JSON(), nullable=True),
    sa.Column('dataset_names', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_records_to_sync', sa.Integer(), nullable=True),
    sa.Column('total_records_to_download', sa.Integer(), nullable=True),
    sa.Column('total_records_to_upload', sa.Integer(), nullable=True),
    sa.Column('records_downloaded', sa.Integer(), nullable=True),
    sa.Column('records_uploaded', sa.Integer(), nullable=True),
    sa.Column('bytes_downloaded', sa.Integer(), nullable=True),
    sa.Column('bytes_uploaded', sa.Integer(), nullable=True),
    sa.Column('dataset_sync_hashes', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_operations_run_id'), 'sync_operations', ['run_id'], unique=True)
    op.create_index(op.f('ix_sync_operations_user_id'), 'sync_operations', ['user_id'], unique=False)
    op.create_table('acls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('principal_id', sa.UUID(), nullable=True),
    sa.Column('permission_id', sa.UUID(), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_data',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('data_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'data_id')
    )
    op.create_table('dataset_database',
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('vector_database_name', sa.String(), nullable=False),
    sa.Column('graph_database_name', sa.String(), nullable=False),
    sa.Column('vector_database_provider', sa.String(), nullable=False),
    sa.Column('graph_database_provider', sa.String(), nullable=False),
    sa.Column('graph_dataset_database_handler', sa.String(), nullable=False),
    sa.Column('vector_dataset_database_handler', sa.String(), nullable=False),
    sa.Column('vector_database_url', sa.String(), nullable=True),
    sa.Column('graph_database_url', sa.String(), nullable=True),
    sa.Column('vector_database_key', sa.String(), nullable=True),
    sa.Column('graph_database_key', sa.String(), nullable=True),
    sa.Column('graph_database_connection_info', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('vector_database_connection_info', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_index(op.f('ix_dataset_database_dataset_id'), 'dataset_database', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_database_owner_id'), 'dataset_database', ['owner_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    op.create_index(op.f('ix_tenants_owner_id'), 'tenants', ['owner_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['principals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_roles_tenant_id_name')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_table('tenant_default_permissions',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['principals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('role_default_permissions',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_default_permissions',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_tenants',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tenants')
    op.drop_table('user_roles')
    op.drop_table('user_default_permissions')
    op.drop_table('role_default_permissions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenant_default_permissions')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_tenants_owner_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_dataset_database_owner_id'), table_name='dataset_database')
    op.drop_index(op.f('ix_dataset_database_dataset_id'), table_name='dataset_database')
    op.drop_table('dataset_database')
    op.drop_table('dataset_data')
    op.drop_table('acls')
    op.drop_index(op.f('ix_sync_operations_user_id'), table_name='sync_operations')
    op.drop_index(op.f('ix_sync_operations_run_id'), table_name='sync_operations')
    op.drop_table('sync_operations')
    op.drop_index(op.f('ix_results_user_id'), table_name='results')
    op.drop_table('results')
    op.drop_table('queries')
    op.drop_table('task_runs')
    op.drop_table('pipeline_task')
    op.drop_table('tasks')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_principals_id'), table_name='principals')
    op.drop_table('principals')
    op.drop_index(op.f('ix_pipeline_runs_pipeline_run_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_pipeline_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_dataset_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_notebooks_owner_id'), table_name='notebooks')
    op.drop_table('notebooks')
    op.drop_index('idx_graph_relationship_ledger_source_node_id', table_name='graph_relationship_ledger')
    op.drop_index('idx_graph_relationship_ledger_destination_node_id', table_name='graph_relationship_ledger')
    op.drop_index('idx_graph_relationship_id', table_name='graph_relationship_ledger')
    op.drop_table('graph_relationship_ledger')
    op.drop_table('graph_metrics')
    op.drop_index(op.f('ix_datasets_tenant_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_owner_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_data_tenant_id'), table_name='data')
    op.drop_index(op.f('ix_data_owner_id'), table_name='data')
    op.drop_table('data')
    # ### end Alembic commands ###
